export const enum TaiwanCity {
  taipei,
  newTaipei,
  taoyuan,
  taichung,
  tainan,
  kaohsiung,
  keelung,
  hsinchu,

  // county
  hsinchuCounty,
  miaoliCounty,
  changhuaCounty,
  nantouCounty,
  yunlinCounty,
  chiayiCounty,
  pingtungCounty,
  yilanCounty,
  hualienCounty,
  taitungCounty,
  kinmenCounty,
  penghuCounty,
  lienchiangCounty,
}

export const TaiwanCityCnLabel = {
  [TaiwanCity.taipei]: '台北市',
  [TaiwanCity.newTaipei]: '新北市',
  [TaiwanCity.taoyuan]: '桃園市',
  [TaiwanCity.taichung]: '台中市',
  [TaiwanCity.tainan]: '台南市',
  [TaiwanCity.kaohsiung]: '高雄市',
  [TaiwanCity.keelung]: '基隆市',
  [TaiwanCity.hsinchu]: '新竹市',
  [TaiwanCity.hsinchuCounty]: '新竹縣',
  [TaiwanCity.miaoliCounty]: '苗栗縣',
  [TaiwanCity.changhuaCounty]: '彰化縣',
  [TaiwanCity.nantouCounty]: '南投縣',
  [TaiwanCity.yunlinCounty]: '雲林縣',
  [TaiwanCity.chiayiCounty]: '嘉義縣',
  [TaiwanCity.pingtungCounty]: '屏東縣',
  [TaiwanCity.yilanCounty]: '宜蘭縣',
  [TaiwanCity.hualienCounty]: '花蓮縣',
  [TaiwanCity.taitungCounty]: '臺東縣',
  [TaiwanCity.kinmenCounty]: '金門縣',
  [TaiwanCity.penghuCounty]: '澎湖縣',
  [TaiwanCity.lienchiangCounty]: '連江縣',
};

export const TaiwanCityEnLabel = {
  [TaiwanCity.taipei]: 'Taipei',
  [TaiwanCity.newTaipei]: 'New Taipei',
  [TaiwanCity.taoyuan]: 'Taoyuan',
  [TaiwanCity.taichung]: 'Taichung',
  [TaiwanCity.tainan]: 'Tainan',
  [TaiwanCity.kaohsiung]: 'Kaohsiung',
  [TaiwanCity.keelung]: 'Keelung',
  [TaiwanCity.hsinchu]: 'Hsinchu',
  [TaiwanCity.hsinchuCounty]: 'Hsinchu County',
  [TaiwanCity.miaoliCounty]: 'Miaoli County',
  [TaiwanCity.changhuaCounty]: 'Changhua County',
  [TaiwanCity.nantouCounty]: 'Nantou County',
  [TaiwanCity.yunlinCounty]: 'Yunlin County',
  [TaiwanCity.chiayiCounty]: 'Chiayi County',
  [TaiwanCity.pingtungCounty]: 'Pingtung County',
  [TaiwanCity.yilanCounty]: 'Yilan County',
  [TaiwanCity.hualienCounty]: 'Hualien County',
  [TaiwanCity.taitungCounty]: 'Taitung County',
  [TaiwanCity.kinmenCounty]: 'Kinmen County',
  [TaiwanCity.penghuCounty]: 'Penghu County',
  [TaiwanCity.lienchiangCounty]: 'Lienchiang County',
};
